import type { Category } from "../types"

export const anillos: Category = {
  slug: "anillos",
  title: "Anillos",
  eyebrow: "Joyería",
  description:
    "Corazones, perlas y destellos pensados para llevar solos o apilados. Ajustables y listos para regalar.",
  heroImage: "/img/anillo-lifestyle-3.webp",
  products: [
    {
      slug: "ola-dorada",
      name: "Ola Dorada",
      description: "Anillo abierto con curva ondulada y circonita.",
      price: 34,
      material: "oro",
      image: "/img/anillos/anillo-ola-dorada.webp",
      badge: "Más vendido",
      addedAt: 3,
    },
    {
      slug: "corazon-fino",
      name: "Corazón Fino",
      description: "Aro delicado rematado con un pequeño corazón.",
      price: 29,
      material: "oro",
      image: "/img/anillos/anillo-corazon-fino.webp",
      addedAt: 5,
    },
    {
      slug: "v",
      name: "Anillo en V",
      description: "Un anillo en V liso y pulido que abraza el dedo.",
      price: 32,
      material: "oro",
      image: "/img/anillos/anillo-v.webp",
      badge: "Nuevo",
      addedAt: 8,
    },
    {
      slug: "duo-corazon",
      name: "Dúo Corazón",
      description: "Pareja de corazones calados en oro y plata.",
      price: 45,
      material: "plata",
      image: "/img/anillos/anillo-duo-corazon.webp",
      addedAt: 4,
    },
    {
      slug: "flor-dorada",
      name: "flor dorada",
      description: "Banda fina con piedra central talla brillante.",
      price: 36,
      material: "oro",
      image: "/img/anillos/anillo-flor-dorada.webp",
      addedAt: 2,
    },
    {
      slug: "anillo-huella",
      name: "Anillo Huella",
      description: "Anillo con diseño de huella de cachorro.",
      price: 42,
      material: "oro",
      image: "/img/anillos/anillo-huella.jpeg",
      badge: "Más vendido",
      addedAt: 1,
    },
    {
      slug: "flor-de-perla",
      name: "Flor de Perla",
      description: "Flor esmaltada en blanco con perla en el centro.",
      price: 39,
      material: "oro",
      image: "/img/anillos/anillo-flor-de-perla.jpeg",
      badge: "Edición limitada",
      addedAt: 7,
    },
    {
      slug: "perla-clasica",
      name: "Perla Clásica",
      description: "Perla cultivada sobre una banda dorada.",
      price: 38,
      material: "oro",
      image: "/img/anillos/anillo-perla-clasica.jpeg",
      badge: "Nuevo",
      addedAt: 6,
    },
  ],
}
