import type { Category } from "../types"

export const brazaletes: Category = {
  slug: "brazaletes",
  title: "Brazaletes",
  eyebrow: "Joyería",
  description:
    "Brazaletes rígidos y de charms con circonitas, nácar y detalles con significado.",
  heroImage: "/img/brazalete-lifestyle-1.webp",
  products: [
    {
      slug: "corazon-pave",
      name: "Corazón Pavé",
      description: "Brazalete rígido con corazón y circonitas.",
      price: 45,
      material: "oro",
      image: "/img/brazaletes/brazalete-corazon-pave.webp",
      badge: "Más vendido",
      addedAt: 5,
    },
    {
      slug: "charms-del-mar",
      name: "Charms del Mar",
      description: "Brazalete de charms marinos.",
      price: 49,
      material: "oro",
      image: "/img/brazaletes/brazalete-charms-del-mar.webp",
      addedAt: 7,
    },
    {
      slug: "charms-jade",
      name: "Charms Jade",
      description: "Charms dorados con cuenta verde.",
      price: 49,
      material: "oro",
      image: "/img/brazaletes/brazalete-charms-jade.webp",
      addedAt: 6,
    },
    {
      slug: "flor-de-sol",
      name: "Flor de Sol",
      description: "Brazalete abierto con flor nacarada.",
      price: 59,
      material: "oro",
      image: "/img/brazaletes/brazalete-flor-de-sol.webp",
      badge: "Edición limitada",
      addedAt: 9,
    },
    {
      slug: "trebol-esbelto",
      name: "Trébol Esbelto",
      description: "Brazalete fino con trébol de nácar.",
      price: 39,
      material: "oro",
      image: "/img/brazaletes/brazalete-trebol-esbelto.webp",
      addedAt: 3,
    },
    {
      slug: "clavo",
      name: "Clavo",
      description: "Brazalete abierto en forma de clavo.",
      price: 42,
      material: "oro",
      image: "/img/brazaletes/brazalete-clavo.webp",
      badge: "Nuevo",
      addedAt: 8,
    },
    {
      slug: "infinito",
      name: "Infinito",
      description: "Brazalete rígido con circonitas e infinito.",
      price: 52,
      material: "oro",
      image: "/img/brazaletes/brazalete-infinito.webp",
      addedAt: 2,
    },
    {
      slug: "charms-llave",
      name: "Charms Llave",
      description: "Charms de llave, candado y flor.",
      price: 49,
      material: "oro",
      image: "/img/brazaletes/brazalete-charms-llave.webp",
      addedAt: 4,
    },
    {
      slug: "charms-corazon",
      name: "Charms Corazón",
      description: "Charms con corazón y ala.",
      price: 49,
      material: "oro",
      image: "/img/brazaletes/brazalete-charms-corazon.webp",
      addedAt: 1,
    },
  ],
}
