import type { Category } from "../types"

export const collares: Category = {
  slug: "collares",
  title: "Collares",
  eyebrow: "Joyería",
  description:
    "Gargantillas rígidas, perlas y tréboles de nácar que enmarcan el escote. Para llevar solos o en capas.",
  heroImage: "/img/modelos/modelo-collar-corazon-perla.webp",
  products: [
    {
      slug: "medalla-grabada",
      name: "Medalla Grabada",
      description: "Medalla rectangular en relieve sobre cadena fina.",
      story:
        "Una medalla rectangular con un dibujo en relieve, colgada de una cadena fina. Tiene el tamaño de una uña y se lleva pegada al cuello o un poco más abajo, según el cierre. Se puede combinar con otra cadena más larga sin que se enreden.",
      price: 6.00,
      soldOut: false,
      material: "oro",
      image: "/img/collares/collar-medalla-grabada.webp",
      addedAt: 3,
    },
    {
      slug: "trebol-de-nacar-set",
      name: "Trébol de Nácar",
      description: "Trébol de nácar sobre una cadena de plata.",
      story:
        "Un trébol de cuatro hojas en nácar blanco sobre cadena de plata. El nácar es natural, así que cada trébol tiene un tono ligeramente distinto. Es un collar para todos los días que también sirve como regalo cuando no sabes muy bien qué regalar.",
      price: 6.00,
      soldOut: false,
      material: "plata",
      image: "/img/collares/collar-trebol-de-nacar.webp",
      badge: "Más vendido",
      addedAt: 9,
    },
    {
      slug: "gardenia",
      name: "Gardenia",
      description: "Gargantilla rígida con flor blanca de resina.",
      story:
        "Una gargantilla rígida, sin cadena, con una flor blanca de resina en el centro. Los pétalos son mates y la flor mide unos dos centímetros. Al ser rígida, se abre por detrás y se coloca directamente sobre el cuello. Va bien con escotes abiertos y con camisetas de cuello redondo.",
      price: 19.00,
      soldOut: true,
      material: "oro",
      image: "/img/collares/collar-gardenia.webp",
      badge: "Edición limitada",
      addedAt: 14,
    },
    {
      slug: "dalia",
      name: "Dalia",
      description: "Gargantilla rígida con flor nacarada.",
      story:
        "Gargantilla rígida con una flor nacarada de pétalos apretados, parecida a una dalia. Es la más llamativa de las gargantillas florales de la colección y la que más se lleva para salir. El nácar brilla más que la resina de la Gardenia, si dudas entre las dos.",
      price: 19.00,
      soldOut: false,
      material: "oro",
      image: "/img/collares/collar-dalia.webp",
      addedAt: 12,
    },
    {
      slug: "trebol-calado",
      name: "Trébol Calado",
      description: "Trébol calado con circonita en cadena fina.",
      story:
        "Un trébol calado, con los bordes en metal y el centro vacío, salvo por una circonita pequeña. Cuelga de una cadena fina. Pesa muy poco y deja ver la piel a través del trébol, así que queda más ligero que los tréboles de nácar.",
      price: 6.00,
      soldOut: false,
      material: "oro",
      image: "/img/collares/collar-trebol-calado.webp",
      addedAt: 5,
    },
    {
      slug: "cascada-de-treboles",
      name: "Cascada de Tréboles",
      description: "Cadena larga salpicada de tréboles de nácar.",
      story:
        "Una cadena larga de plata con varios tréboles de nácar repartidos a lo largo. Se puede llevar suelta, a la altura del pecho, o dar dos vueltas y usarla como collar corto. Los tréboles no están todos a la misma distancia, y eso hace que caiga de forma menos uniforme.",
      price: 6.00,
      soldOut: false,
      material: "plata",
      image: "/img/collares/collar-cascada-de-treboles.webp",
      addedAt: 7,
    },
    {
      slug: "petalos",
      name: "Pétalos",
      description: "Cadena de eslabones con pétalos dorados.",
      story:
        "Una cadena de eslabones con pétalos dorados intercalados. Los pétalos son planos y pulidos, y captan la luz al moverse. Es un collar más de estructura que de colgante: no tiene un elemento central, sino que toda la cadena es el diseño.",
      price: 6.00,
      soldOut: true,
      material: "oro",
      image: "/img/collares/collar-petalos.webp",
      addedAt: 4,
    },
    {
      slug: "doble-corazon",
      name: "Doble Corazón",
      description: "Dos cadenas con corazones esmaltados.",
      style: "doble",
      story:
        "Dos cadenas de distinta longitud que se ponen juntas, cada una con un corazón esmaltado. Vienen unidas por el cierre, así que no hay que combinarlas ni ajustarlas. El esmalte es de color y añade un punto que el metal solo no tiene.",
      price: 7.00,
      soldOut: false,
      material: "oro",
      image: "/img/collares/collar-doble-corazon.webp",
      badge: "Nuevo",
      addedAt: 15,
    },
    {
      slug: "cristal",
      name: "Cristal",
      description: "Doble hilo transparente con gota colgante.",
      style: "doble",
      story:
        "Dos hilos transparentes, casi invisibles sobre la piel, con una gota de cristal colgante. Desde lejos parece que la gota flota en el cuello. Es el collar más económico de la colección y uno de los que más se repiten en pedidos.",
      price: 7.00,
      soldOut: false,
      material: "plata",
      image: "/img/collares/collar-cristal.webp",
      addedAt: 2,
    },
    {
      slug: "perla-barroca",
      name: "Perla Barroca",
      description: "Perla barroca en cadena ajustable tipo lazo.",
      story:
        "Una perla barroca, es decir, de forma irregular, colgada de una cadena ajustable tipo lazo. Cada perla es diferente porque no son redondas ni simétricas. Se ajusta tirando de un extremo, sin cierre, y sirve tanto corto como largo.",
      price: 7.00,
      soldOut: false,
      material: "oro",
      image: "/img/collares/collar-perla-barroca.webp",
      addedAt: 8,
    },
    {
      slug: "perla-y-corazon",
      name: "Perla y Corazón",
      description: "Dos vueltas: hilo de perlas y corazón dorado.",
      style: "doble",
      story:
        "Dos vueltas en un solo collar: un hilo de perlas pequeñas y una cadena dorada con un corazón. Las dos capas se llevan juntas y quedan a alturas distintas. Es el tipo de collar que resuelve el look sin tener que añadir nada más.",
      price: 7.00,
      soldOut: false,
      material: "oro",
      image: "/img/collares/collar-perla-y-corazon.webp",
      badge: "Más vendido",
      addedAt: 10,
    },
    {
      slug: "trebol-clasico",
      name: "Trébol Clásico",
      description: "Trébol de nácar sobre cadena dorada.",
      story:
        "El mismo trébol de nácar que en la versión de plata, aquí sobre cadena dorada. El blanco del nácar contrasta más con el dorado que con la plata, así que se ve algo más desde lejos. Cadena fina, cierre de mosquetón.",
      price: 6.00,
      soldOut: false,
      material: "oro",
      image: "/img/collares/collar-trebol-clasico.webp",
      addedAt: 6,
    },
    {
      slug: "corazon-filigrana",
      name: "Corazón Filigrana",
      description: "Colgante de corazón con filigrana.",
      story:
        "Un colgante de corazón hecho con hilos de metal entrelazados, al estilo de la filigrana tradicional. Se ve a través de él. Es una pieza que suele gustar a quienes prefieren joyas con algo de trabajo artesanal a la vista.",
      price: 6.00,
      soldOut: true,
      material: "oro",
      image: "/img/collares/collar-corazon-filigrana.webp",
      addedAt: 1,
    },
    {
      slug: "lazo-de-perla",
      name: "Lazo de Perla",
      description: "Cadena serpiente rematada con una perla.",
      story:
        "Una cadena tipo serpiente, plana y flexible, que termina en una perla. La cadena brilla de forma continua, sin eslabones a la vista, y la perla queda justo en el centro. Se lleva corta.",
      price: 7.00,
      soldOut: true,
      material: "oro",
      image: "/img/collares/collar-lazo-de-perla.webp",
      badge: "Nuevo",
      addedAt: 16,
    },
    {
      slug: "lirio",
      name: "Lirio",
      description: "Gargantilla rígida con flor de lirio.",
      story:
        "Gargantilla rígida con una flor de lirio en el centro. El lirio tiene los pétalos más largos y abiertos que la Gardenia o la Dalia, así que ocupa más espacio en el cuello. Es la gargantilla que más se usa con vestidos de tirantes.",
      price: 7.00,
      soldOut: true,
      material: "oro",
      image: "/img/collares/collar-lirio.webp",
      addedAt: 11,
    },
    {
      slug: "constelacion",
      name: "Constelación",
      description: "Gargantilla de circonitas engastadas.",
      story:
        "Una gargantilla de circonitas engastadas en fila, sin huecos entre ellas. Es el collar con más brillo de la tienda y el de precio más alto. Para bodas, cenas y fotos con flash. Cierre ajustable en varias posiciones.",
      price: 19.00,
      soldOut: true,
      material: "oro",
      image: "/img/collares/collar-constelacion.webp",
      badge: "Edición limitada",
      addedAt: 13,
    },
  ],
}
