import type { Category } from "../types"

export const collares: Category = {
  slug: "collares",
  title: "Collares",
  eyebrow: "Joyería",
  description:
    "Gargantillas rígidas, perlas y tréboles de nácar que enmarcan el escote. Para llevar solos o en capas.",
  heroImage: "/img/collar-lifestyle-1.jpg",
  products: [
    {
      slug: "medalla-grabada",
      name: "Medalla Grabada",
      description: "Medalla rectangular en relieve sobre cadena fina.",
      price: 42,
      material: "oro",
      image: "/img/collares/collar-medalla-grabada.webp",
      addedAt: 3,
    },
    {
      slug: "trebol-de-nacar",
      name: "Trébol de Nácar",
      description: "Trébol de nácar sobre una cadena de plata.",
      price: 36,
      material: "plata",
      image: "/img/collares/collar-trebol-de-nacar.webp",
      badge: "Más vendido",
      addedAt: 9,
    },
    {
      slug: "gardenia",
      name: "Gardenia",
      description: "Gargantilla rígida con flor blanca de resina.",
      price: 58,
      material: "oro",
      image: "/img/collares/collar-gardenia.webp",
      badge: "Edición limitada",
      addedAt: 14,
    },
    {
      slug: "dalia",
      name: "Dalia",
      description: "Gargantilla rígida con flor nacarada.",
      price: 62,
      material: "oro",
      image: "/img/collares/collar-dalia.webp",
      addedAt: 12,
    },
    {
      slug: "trebol-calado",
      name: "Trébol Calado",
      description: "Trébol calado con circonita en cadena fina.",
      price: 39,
      material: "oro",
      image: "/img/collares/collar-trebol-calado.webp",
      addedAt: 5,
    },
    {
      slug: "cascada-de-treboles",
      name: "Cascada de Tréboles",
      description: "Cadena larga salpicada de tréboles de nácar.",
      price: 55,
      material: "plata",
      image: "/img/collares/collar-cascada-de-treboles.webp",
      addedAt: 7,
    },
    {
      slug: "petalos",
      name: "Pétalos",
      description: "Cadena de eslabones con pétalos dorados.",
      price: 49,
      material: "oro",
      image: "/img/collares/collar-petalos.webp",
      addedAt: 4,
    },
    {
      slug: "doble-corazon",
      name: "Doble Corazón",
      description: "Dos cadenas con corazones esmaltados.",
      price: 46,
      material: "oro",
      image: "/img/collares/collar-doble-corazon.webp",
      badge: "Nuevo",
      addedAt: 15,
    },
    {
      slug: "cristal",
      name: "Cristal",
      description: "Doble hilo transparente con gota colgante.",
      price: 29,
      material: "plata",
      image: "/img/collares/collar-cristal.webp",
      addedAt: 2,
    },
    {
      slug: "perla-barroca",
      name: "Perla Barroca",
      description: "Perla barroca en cadena ajustable tipo lazo.",
      price: 44,
      material: "oro",
      image: "/img/collares/collar-perla-barroca.webp",
      addedAt: 8,
    },
    {
      slug: "perla-y-corazon",
      name: "Perla y Corazón",
      description: "Dos vueltas: hilo de perlas y corazón dorado.",
      price: 52,
      material: "oro",
      image: "/img/collares/collar-perla-y-corazon.webp",
      badge: "Más vendido",
      addedAt: 10,
    },
    {
      slug: "trebol-clasico",
      name: "Trébol Clásico",
      description: "Trébol de nácar sobre cadena dorada.",
      price: 38,
      material: "oro",
      image: "/img/collares/collar-trebol-clasico.webp",
      addedAt: 6,
    },
    {
      slug: "corazon-filigrana",
      name: "Corazón Filigrana",
      description: "Colgante de corazón con filigrana.",
      price: 41,
      material: "oro",
      image: "/img/collares/collar-corazon-filigrana.webp",
      addedAt: 1,
    },
    {
      slug: "lazo-de-perla",
      name: "Lazo de Perla",
      description: "Cadena serpiente rematada con una perla.",
      price: 45,
      material: "oro",
      image: "/img/collares/collar-lazo-de-perla.jpeg",
      badge: "Nuevo",
      addedAt: 16,
    },
    {
      slug: "lirio",
      name: "Lirio",
      description: "Gargantilla rígida con flor de lirio.",
      price: 54,
      material: "oro",
      image: "/img/collares/collar-lirio.jpg",
      addedAt: 11,
    },
    {
      slug: "constelacion",
      name: "Constelación",
      description: "Gargantilla de circonitas engastadas.",
      price: 69,
      material: "oro",
      image: "/img/collares/collar-constelacion.jpg",
      badge: "Edición limitada",
      addedAt: 13,
    },
  ],
}
