import type { Category } from "../types"

export const pendientes: Category = {
  slug: "pendientes",
  title: "Pendientes",
  eyebrow: "Joyería",
  description:
    "Desde botones mínimos hasta aros con cristal: piezas ligeras para el día a día o para brillar de noche.",
  heroImage: "/img/aretes-lifestyle-1.webp",
  products: [
    {
      slug: "cono-de-cristal",
      name: "Cono de Cristal",
      description: "Ganchos con cono dorado y cuarzo facetado.",
      price: 29,
      material: "oro",
      image: "/img/pendientes/aretes-cono-de-cristal.webp",
      addedAt: 3,
    },
    {
      slug: "gota-dorada",
      name: "Gota Dorada",
      description: "Gota maxi con acabado espejo.",
      price: 32,
      material: "oro",
      image: "/img/pendientes/aretes-gota-dorada.webp",
      badge: "Más vendido",
      addedAt: 9,
    },
    {
      slug: "aro-medallon",
      name: "Aro Medallón",
      description: "Aro con medallón de nácar.",
      price: 34,
      material: "oro",
      image: "/img/pendientes/aretes-aro-medallon.webp",
      addedAt: 6,
    },
    {
      slug: "aro-cuarzo",
      name: "Aro Cuarzo",
      description: "Aro con cristal facetado colgante.",
      price: 33,
      material: "oro",
      image: "/img/pendientes/aretes-aro-cuarzo.webp",
      addedAt: 5,
    },
    {
      slug: "trebol-nacar-mini",
      name: "Trébol de Nácar Mini",
      description: "Trébol de nácar blanco en forma de mini.",
      price: 19,
      material: "oro",
      image: "/img/pendientes/aretes-trebol-nacar-mini.webp",
      addedAt: 11,
    },
    {
      slug: "colibri",
      name: "Colibrí",
      description: "Botón en forma de colibrí.",
      price: 21,
      material: "oro",
      image: "/img/pendientes/aretes-colibri.webp",
      badge: "Nuevo",
      addedAt: 14,
    },
    {
      slug: "trebol-de-nacar",
      name: "Trébol de Nácar",
      description: "Botón de trébol con nácar blanco.",
      price: 24,
      material: "oro",
      image: "/img/pendientes/aretes-trebol-de-nacar.webp",
      badge: "Más vendido",
      addedAt: 8,
    },
    {
      slug: "luna-de-nacar",
      name: "Luna de Nácar",
      description: "Botón redondo de nácar.",
      price: 22,
      material: "plata",
      image: "/img/pendientes/aretes-luna-de-nacar.webp",
      addedAt: 4,
    },
    {
      slug: "set-corazones",
      name: "Set Corazones",
      description: "Set de tres pares de corazones.",
      price: 35,
      material: "oro",
      image: "/img/pendientes/aretes-set-corazones.webp",
      addedAt: 7,
    },
    {
      slug: "arbol-de-la-vida",
      name: "Árbol de la Vida",
      description: "Botón con forma de árbol de la vida.",
      price: 20,
      material: "oro",
      image: "/img/pendientes/aretes-arbol-de-la-vida.webp",
      addedAt: 10,
    },
    {
      slug: "cuarzo-rosa",
      name: "Cuarzo Rosa",
      description: "Botón triangular de cuarzo rosa.",
      price: 26,
      material: "plata",
      image: "/img/pendientes/aretes-cuarzo-rosa.webp",
      addedAt: 12,
    },
    {
      slug: "mariposa-blanca",
      name: "Mariposa Blanca",
      description: "Botón en forma de mariposa blanca.",
      price: 23,
      material: "oro",
      image: "/img/pendientes/aretes-mariposa-blanca.webp",
      addedAt: 2,
    },
    {
      slug: "pave-corazon",
      name: "Pavé Corazón",
      description: "Corazón con pavé de circonitas.",
      price: 28,
      material: "oro",
      image: "/img/pendientes/aretes-pave-corazon.webp",
      badge: "Nuevo",
      addedAt: 15,
    },
    {
      slug: "set-planetario",
      name: "Set Planetario",
      description: "Set de botones con circonitas y estrella.",
      price: 39,
      material: "oro",
      image: "/img/pendientes/aretes-set-planetario.webp",
      badge: "Edición limitada",
      addedAt: 13,
    },
    {
      slug: "set-perla",
      name: "Set Perla",
      description: "Set de perlas y botones dorados.",
      price: 36,
      material: "oro",
      image: "/img/pendientes/aretes-set-corazon-perla.webp",
      addedAt: 1,
    },
  ],
}
