import type { Category } from "../types"

export const pulseras: Category = {
  slug: "pulseras",
  title: "Pulseras",
  eyebrow: "Joyería",
  description:
    "Cadenas finas, perlas y tréboles para apilar en la muñeca. Ajustables y cómodas de llevar.",
  heroImage: "/img/pulsera-lifestyle-1.webp",
  products: [
    {
      slug: "riviera",
      name: "Riviera",
      description: "Cadena de circonitas engastadas.",
      price: 38,
      material: "plata",
      image: "/img/pulseras/pulsera-riviera.webp",
      badge: "Más vendido",
      addedAt: 5,
    },
    {
      slug: "serpiente",
      name: "Serpiente",
      description: "Cadena serpiente con medalla colgante.",
      price: 29,
      material: "oro",
      image: "/img/pulseras/pulsera-serpiente.webp",
      addedAt: 3,
    },
    {
      slug: "globo",
      name: "Globo",
      description: "Cadena fina con charm de perrito globo.",
      price: 34,
      material: "oro",
      image: "/img/pulseras/pulsera-globo.webp",
      badge: "Nuevo",
      addedAt: 9,
    },
    {
      slug: "perlas-ajustable",
      name: "Perlas Ajustable",
      description: "Cadena fina con perlas y cierre deslizante.",
      price: 27,
      material: "oro",
      image: "/img/pulseras/pulsera-perlas-ajustable.webp",
      addedAt: 6,
    },
    {
      slug: "trebol-blanco",
      name: "Trébol Blanco",
      description: "Tréboles de nácar blanco enlazados.",
      price: 42,
      material: "oro",
      image: "/img/pulseras/pulsera-trebol-blanco.webp",
      badge: "Más vendido",
      addedAt: 7,
    },
    {
      slug: "trebol-negro",
      name: "Trébol Negro",
      description: "Tréboles de ónix enlazados.",
      price: 42,
      material: "oro",
      image: "/img/pulseras/pulsera-trebol-negro.webp",
      addedAt: 8,
    },
    {
      slug: "mariposa-de-perlas",
      name: "Mariposa de Perlas",
      description: "Varias vueltas de perlas con mariposa.",
      price: 48,
      material: "oro",
      image: "/img/pulseras/pulsera-mariposa-de-perlas.webp",
      badge: "Edición limitada",
      addedAt: 4,
    },
    {
      slug: "placas",
      name: "Placas",
      description: "Cadena con placas pulidas.",
      price: 31,
      material: "oro",
      image: "/img/pulseras/pulsera-placas.webp",
      addedAt: 2,
    },
    {
      slug: "eslabones",
      name: "Eslabones",
      description: "Cadena de eslabones con cierre de corazones.",
      price: 36,
      material: "oro",
      image: "/img/pulseras/pulsera-eslabones.webp",
      addedAt: 1,
    },
  ],
}
